### PR TITLE
Update libs and support additional targets

### PR DESCRIPTION
**Pull request by aftabahmadTW**
Based on the issue created here: https://github.com/comahe-de/i18n4k/issues/14

### Changes
- Update gradle and libraries
- Add the new targets for apple silicon

### CODE REVIEW

**Comment by comahe-de** [comment]
Thanks for your contribution!

Version v0.4.0 will be available in Maven Central in about 2 days.

**Comment by comahe-de** [comment]
@aftabahmadTW The release may take a while, as there is a new problem with Kotlin 1.6.21: #17

**Comment by aftabahmadTW** [comment]
Ahh okay, I can take a look to see what's causing that

**Comment by comahe-de** [comment]
@aftabahmadTW 

> I can take a look to see what's causing that

When adding this to the `build.gradle.kts` it seams to work

        nativeCommonMain.dependsOn(commonMain)
        nativeCommonTest.dependsOn(commonTest)

> By the way is there a place to have larger discussions around the libray?

It is always OK to open an issue to discuss it or make an PR. Sorry for not responding to your issue. I just forgot it.

>  I think it's worth having a seperate one for iOS.

See new issue:  #18

**Pull request merged**
